apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
        - name: game-service
          image: sebe20/game-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              value: postgresql://user:pass@postgres:5432/rps
